Feature/library
Persatyi/book-read-frontend pull request #5
Opened 2022-07-15 08:28 UTC by andrpoch

Зробив:
 Інпути для додавання книжок
Валідація інпутів
Модалка 
BookList(ще не дороблений тому його не перевіряти, тому що не знаю чи встигну сьогодні) !!!
І чи буде background-color на body?

2022-07-15 10:04 UTC, Persatyi reviewed
Всі спрайти знаходяться в assets/images/sprite. звідти все імпортуєш, якшо твого спрайта нема то просто закидуєш код в цей файл, якшо не знаєш як то питай

2022-07-15 10:04 UTC, Persatyi commented on src/App.js
> +import React from "react";
змінна яка ніде не використовується

2022-07-15 10:04 UTC, Persatyi commented on src/App.js
> +import LibraryPage from "pages/LibraryPage";
тут не треба міняти назву
поверни на import Library from "pages/Library";

2022-07-15 10:04 UTC, Persatyi commented on src/App.js
> +        <Route path="/library" element={<LibraryPage />} />
повернути на <Route path="/library" element={<Library />} />

2022-07-15 10:04 UTC, Persatyi commented on src/assets/images/library/Back.jsx
> +</svg>
для SVG у нас є  assets/images/sprite.svg - закинь цей код туди і імпортуй як файл

2022-07-15 10:04 UTC, Persatyi commented on src/assets/images/library/Plus.jsx
> +</svg>
для SVG у нас є assets/images/sprite.svg - закинь цей код туди і імпортуй як файл

2022-07-15 10:04 UTC, Persatyi commented on src/components/Library/Library.module.scss
> +@import "stylesheet/shared.scss";
Всі імпорти є в index.scss в корні

2022-07-15 10:04 UTC, Persatyi commented on src/components/LibraryModal/LibraryModal.module.scss
> +@import "stylesheet/shared.scss";
така ж історія

2022-07-15 10:04 UTC, Persatyi commented on src/components/Modal/Modal.module.scss
> +@import "../../stylesheet/shared.scss";
те саме

2022-07-15 10:04 UTC, Persatyi commented on src/stylesheet/shared.scss
> +@import "./vars";
Файл з імпортами вже є в корні index.scss

2022-07-15 10:04 UTC, Persatyi commented on src/components/BookList/BookList.jsx
> +                     <li className={s.readBookItem}></li>
ця лішка не може бути окремо вона повинна бути загорнута в ul,
браузрер поченає помилки сипати

2022-07-15 10:05 UTC, Persatyi requested changes
Твою гілку я оновив, з main запулив всі зміни

2022-07-15 18:22 UTC, Selim96 commented on src/assets/images/library/Back.jsx
> +</svg>
якщо це про стрилочку , то у спрайті є ця іконка

2022-07-15 18:23 UTC, Selim96 commented on src/assets/images/library/Plus.jsx
> +</svg>
плюсик я теж закидав

2022-07-18 08:50 UTC, Persatyi approved these changes

2022-07-18 08:50 UTC, Persatyi commented on public/index.html
> +    <div id="modal-root"></div>
а шо це за шлях?

2022-07-18 08:50 UTC, merged